#include "nsISupports.idl"

[scriptable, uuid(dff4b554-d1fb-4291-b390-d7a707a2af42)]
interface totemIGMPNetwork : nsISupports
{
  /* Documentation at
   * http://msdn.microsoft.com/library/en-us/wmpsdk11/mmp_sdk/networkobject.asp */
};
