
#include "nsISupports.idl"

[scriptable, uuid(37e45753-308a-443e-8381-a4306ec32838)]
interface totemIGMPMediaCollection : nsISupports
{
  /* Documentation at
   * http://msdn.microsoft.com/library/en-us/wmpsdk11/mmp_sdk/mediacollectionobject.asp */
};
