
#include "nsISupports.idl"

[scriptable, uuid(3f7b6b21-b154-40c3-8d26-3a5edf75c782)]
interface totemIGMPDVD : nsISupports
{
  /* Documentation at
   * http://msdn.microsoft.com/library/en-us/wmpsdk11/mmp_sdk/dvdobject.asp */
};
