/*
 *  Copyright © 2007, Bastien Nocera <hadess@hadess.net
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the
 *  Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 *  Boston, MA 02111-1307, USA.
 */

#include "nsISupports.idl"

[scriptable, uuid(29bef4c8-124b-418f-a47a-64411a6b8f66)]
interface totemIGMPSettings : nsISupports
{
  /* Documentation at
   * http://msdn.microsoft.com/library/en-us/wmpsdk11/mmp_sdk/settingsobject.asp */
  attribute boolean autoStart;
  attribute long balance;
  attribute AUTF8String baseURL;
  readonly attribute long defaultAudioLanguage;
  attribute AUTF8String defaultFrame;
  attribute boolean enableErrorDialogs;
  boolean getMode (in ACString modeName);
  attribute boolean invokeURLs;
  boolean isAvailable (in ACString name);
  readonly attribute ACString mediaAccessRights;
  attribute boolean mute;
  attribute long playCount;
  attribute double rate;
  boolean requestMediaAccessRights (in ACString access);
  void setMode (in ACString modeName, in boolean state);
  attribute long volume;
};
