
#include "nsISupports.idl"

[scriptable, uuid(10a1a7e9-ea1f-476a-aa00-475485ea2b93)]
interface totemIGMPCdromCollection : nsISupports
{
    /* Documentation at
     * http://msdn.microsoft.com/library/en-us/wmpsdk11/mmp_sdk/cdromcollectionobject.asp */
};
