
#include "nsISupports.idl"

[scriptable, uuid(6c47177a-d2cf-46f4-9d73-68589d9acaf5)]
interface totemIGMPClosedCaption : nsISupports
{
    /* Documentation at
     * http://msdn.microsoft.com/library/en-us/wmpsdk11/mmp_sdk/closedcaptionobject.asp */
};
