/*
 *  Copyright © 2006-2007, Bastien Nocera <hadess@hadess.net
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the
 *  Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 *  Boston, MA 02111-1307, USA.
 */

#include "nsISupports.idl"

interface totemIGMPPlaylist;
interface totemIGMPPlaylistArray;

[scriptable, uuid(1c97e3ac-1e9d-44c6-8462-95318de3e07a)]
interface totemIGMPPlaylistCollection : nsISupports
{
  /* Documentation at
   * http://msdn.microsoft.com/library/en-us/wmpsdk11/mmp_sdk/playlistcollectionobject.asp */
  totemIGMPPlaylistArray getAll ();
  totemIGMPPlaylistArray getByName (in AUTF8String name);
  totemIGMPPlaylist importPlaylist (in totemIGMPPlaylist playlist);
  boolean isDeleted (in totemIGMPPlaylist playlist);
  totemIGMPPlaylist newPlaylist (in AUTF8String name);
  void remove (in totemIGMPPlaylist playlist);
  void setDeleted (in totemIGMPPlaylist playlist, in boolean true);
};

