.\" Copyright (C) 2014 Milan Kupcevic <milan@physics.harvard.edu>
.\"
.\" This file is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This file is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License 
.\" along with this; if not write to the Free Software Foundation, Inc.
.\" 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
.TH totem\-audio\-preview 1 "2014\-06\-08" "GNOME" "User Commands"
.SH NAME
totem\-audio\-preview \- play audio files
.SH SYNOPSIS
.B totem\-audio\-preview
.RI [ OPTION ]... " " [ FILE ]...
.SH DESCRIPTION
.B totem\-audio\-preview 
is primarily used by GNOME applications for audio preview purposes.
.SH OPTIONS
.TP
.B \-h, \-\-help
Display help.
.TP
.B \-\-help-gst
Display GStreamer options.
.TP
.B \-m, \-\-mimetype
Display supported mime\-types.
.TP
.B \-\-g\-fatal\-warnings
Make all warnings fatal.
.PP
When no FILE is specified, read standard input.
.SH AUTHOR
.B totem\-audio\-preview 
was written by Bastien Nocera <hadess@hadess.net>.
.PP 
This manual page was written by Milan Kupcevic for the Debian Project.
.SH SEE ALSO
.PP
.BR \%totem\-video\-thumbnailer (1),
.BR \%totem (1), 
.BR \%nautilus (1)
