.\" Copyright (C) 2004 Andre Lehovich <andrel@u.arizona.edu>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License 
.\" along with this; if not write to the Free Software Foundation, Inc.
.\" 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
.TH totem 1 "2004\-04\-07" "GNOME"
.SH NAME
totem \- GNOME-desktop movie player based on the xine backend
.SH SYNOPSIS
.B totem
.RI [ option... ] " " [ filenames | URI ]
.SH DESCRIPTION
.B totem
is a movie player for the GNOME desktop.  Through use of the
.B xine
backend many popular file and streaming formats are supported including:
MPEG audio and video (MP3/MPV), Ogg, AVI, ASF, MOV, WMV,
Quicktime, and more.  Playing of DVD and VCD media is
usually possible if you have the appropriate drive.
Although primarily intended as a movie player,
.B totem
can also play many audio formats.
.P
For additional documentation on interactive use of 
.B totem
select the
.I Help
menu option.  The menus allow access to some features not
available through keybindings or command-line options.
.SH OPTIONS
.TP
.B --usage
Output a brief synopsis of command options then quit.
.TP
.B \-?, --help
Output a longer help message then quit.  (Any discrepancies
between this man page and the output of
.B totem --help
should be reported as a documentation bug.)
.TP
.B --version
Output version information then quit.
.P
The following options command an already running instance of
.B totem
to do something; they are useful for remote-control scripting:
.TP
.B --play-pause
Tell an already running instance of 
.B totem
to toggle between play and pause.
.TP
.B --play
Tell an already running instance of
.B totem
to play (has no effect if already playing)
.TP
.B --pause
Tell an already running instance of
.B totem
to pause (has no effect if already paused)
.TP
.B --next
Tell an already running instance of 
.B totem
to skip to the next movie or chapter in the playlist.
.TP
.B --previous
Tell an already running instance of 
.B totem
to return to the previous movie or chapter in the playlist.
.TP
.B --seek-fwd
Tell an already running instance of 
.B totem
to seek forwards 15 seconds in the current movie.
.TP
.B --seek-bwd
Tell an already running instance of 
.B totem
to seek backwards 15 seconds in the current movie.
.TP
.B --volume-up
Tell an already running instance of 
.B totem
to raise the volume by 8%.
.TP
.B --volume-down
Tell an already running instance of 
.B totem
to lower the volume by 8%.
.TP
.B --fullscreen
Tell an already running instance of 
.B totem
to toggle fullscreen mode.
.TP
.B --quit
Tell an already running instance of
.B totem
to quit.
.TP
.BI "--enqueue " filename|URI
Tell an already running instance of totem to add a new stream
to the playlist.
.TP
.BI "--replace " filename|URI
Tell an already running instance of totem to play 
from the playlist.
.P
The following options are standard to applications using the
GDK and GTK+ libraries:
.TP
.BI --gdk-debug= flags
GDK debugging flags to set.
.TP
.BI --gdk-no-debug= flags
GDK debugging flags to unset.
.TP
.BI --display= display
X display to use
.TP
.BI --screen= screen
X screen to use.
.TP
.BI --sync
Make X calls synchronous to facilitate debugging.
.TP
.BI --name= name
Program name as used by the window manager.
.TP
.BI --class= class
Program class a sused by the window manager.
.TP
.BI --gxid-host= host
.TP
.BI --gxid-port= port
.TP
.B --g-fatal-warnings
Make all warnings fatal.
.TP
.BI --gtk-debug= flags
GTK+ debugging flags to set.
.TP
.BI --gtk-no-debug= flags
GTK+ debugging flags to unset
.TP
.BI --gtk-module= module
Load an additional GTK module.
.P
The following options are for Bonobo activation support
.TP
.BI --oaf-ior-fd= fd
File descriptor to print IOR on
.TP
.BI --oaf-activate-iid= iid
IID to activate.
.TP
.BI --oaf-private
Prevent registering of server with OAF
.P
The following are standard GNOME options:
.TP
.BI --disable-sound
Disable sound server use.
.TP
.BI --enable-sound
Enable sound server use.
.TP
.BI --espeaker= hostname : port
Specify the host and port on which the sound server is listening.
.TP
.BI --disable-crash-dialog
Disable the crash-reporting dialog.
.P
The following options are for session management:
.TP
.BI --sm-client-id= ID
Specify session management ID
.TP
.BI --sm-config-prefix= prefix
Specify prefix of saved configuration
.TP
.BI --sm-disable
Disable connecting to session manager.
.SH KEYBINDINGS
Global keybindings for
.BR totem :
.P
.ta \w'Down-arrow   'u	
i	toggle interlacing on and off
.br
a	cycle between aspect ratios
.br
p	toggle between play and pause
.br
Esc	exit full screen mode
.br
f	toggle full screen
.br
h	toggle display of on-screen controls
.br
0	resize window to 50% original size
.br
1	resize window to 100% original size
.br
2	resize window to 200% original size
.br
.br
r	zoom in the video
.br
t	zoom out the video
.br
d	start and stop the telestrator (drawing) mode
.br
e	erase the drawing
.br
Left-arrow        skip back 15 seconds
.br
Right-arrow       skip forward 15 seconds
.br
Shift+Left-arrow  skip back 5 seconds
.br
Shift+Right-arrow skip forward 15 seconds
.br
Ctrl+Left-arrow   skip back 3 minutes
.br
Ctrl+Right arrow  skip forward 10 minutes
.br
s	show the "Skip to..." dialog
.br
Up-arrow	increase volume by 8%
.br
Down-arrow	decrease volume by 8%
.br
b		jump back to previous chapter/movie in playlist
.br
n		jump to next chapter/movie in playlist
.br
q		quit
.br
s		show the "skip to" dialog
.br
.br
Ctrl-E          eject the playing optical media
.br
Ctrl-O		open a new file
.br
Ctrl-L		open a new URI
.br
Ctrl-P		toggle display of the playlist
.br
m		show the DVD menu
.br
c		show the DVD chapter menu
.SH BUGS
.B totem
cannot play files using some proprietary codecs.
.SH AUTHOR
.B totem
was written by Bastien Nocera <hadess@hadess.net>.
This manual page was written by Andre Lehovich for the
Debian Project.
.SH DISTRIBUTION
The latest version of Totem may be downloaded from
.UR http://www.hadess.net/totem.php3
<http://www.hadess.net/totem.php3>
.UE
.SH SEE ALSO
.BR "totem-video-thumbnailer" (1),
.BR xine (1)
.P
The online documentation available through the program's
.I Help
menu.
